"""В таблицу AuthData добавлены столбцы для сохранения персонального токена и персонального ID пользователя на конкретном сайте

Revision ID: 384bb91a91c4
Revises: 
Create Date: 2024-09-18 13:14:47.246716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384bb91a91c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_datas', sa.Column('site_token', sa.String(), nullable=True))
    op.add_column('auth_datas', sa.Column('site_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_datas', 'site_id')
    op.drop_column('auth_datas', 'site_token')
    # ### end Alembic commands ###
